global using System.Text.Json;
global using FluentAssertions;
global using Microsoft.VisualStudio.TestTools.UnitTesting;
global using ToolBX.CoinFlip;
global using ToolBX.Dummies;
global using ToolBX.Dummies.Customizations;
global using ToolBX.OutWarden;
global using ToolBX.Reflection4Humans.Extensions;
global using WhiteJackalStudio.TestTools;